### ISSUE TITLE
Document setting up a local kubernetes development environment

### ISSUE THREAD

**Issue by patchandpray** [dokc/how-to-dok#1]
For developing data use cases on kubernetes we need a local development environment. Let's look into minikube and k3d and document the steps and sources used to setting up a local kubernetes dev environment.

Ideally we would have a markdown document describing these steps and sources which we can link to and re-use across this repository.

**Comment by patchandpray** [comment]
I was thinking this can also just be some references to some good articles or info about setting up the local environment

**Comment by bradmccoydev** [comment]
Hey @patchandpray Im keen to pick this one up...

**Comment by AbhijithGanesh** [comment]
Actually, after yesterday's synchronous meeting, I agreed to work on this and I started documenting my journey. I will be writing a full-fledged blog, so feel free to give me more inputs folks and 
Heyy @bradmccoydev I might contact you if I run into errors

**Comment by shreemaan-abhishek** [comment]
@bradmccoydev are you still available to work on this? If yes, I can assign it to you!!

**Comment by AbhijithGanesh** [comment]
@shreemaan-abhishek I've written a couple of blogs 

some them would be
[blog-1](https://dev.to/abhijithganesh/how-to-run-cassandra-container-locally-56bk)
[blog-2](https://t.co/RYqtaMqNSK)

Most of the setting up parts have been documented, they need to be added to our read me file .
