### ISSUE TITLE
[Issue]: Minor issues in `Knowledge needed` list in README.md file.

### ISSUE THREAD

**Issue by shreemaan-abhishek** [dokc/how-to-dok#12]
### Issue

There are some techs missing from the `Knowledge needed` list.

### What happened?

There are some techs like Docker/Containerization, Node.js, and Express.js missing from the `Knowledge needed` list.

**Comment by shreemaan-abhishek** [comment]
Err, how do I remove labels from the issue.

**Comment by AbhijithGanesh** [comment]
Is it necessary to remove labels?

**Comment by shreemaan-abhishek** [comment]
Not really, but the labels added to this issue are very irrelevant.

**Comment by verma-kunal** [comment]
> Err, how do I remove labels from the issue.

**Comment by shreemaan-abhishek** [comment]
@patchandpray could you please add the  hacktoberfest-accepted label?
