### ISSUE TITLE
[Idea]: Addition of all contributors

### ISSUE THREAD

**Issue by AbhijithGanesh** [dokc/how-to-dok#19]
### Idea

Contributors to be added to readme

### Elaboration

We can use the all contributors bot/plugin to maintain list of contributors.

### Further Details/ Image and Video Based suggestion
https://allcontributors.org/

**Comment by ShivamTyagi12345** [comment]
i can help with this

**Comment by kaiwalyakoparkar** [comment]
I see this issue has been taken care of in #20 PR which is merged so I will close this issue
