### ISSUE TITLE
Setup K8ssandra on local dev cluster

### ISSUE THREAD

**Issue by patchandpray** [dokc/how-to-dok#2]
As part of the use case we want to develop we want to check if we for our Kubernetes native DB we can use https://k8ssandra.io/

Ideally the outcome of this issue would be a document describing some of the features and advantages of using k8ssandra on kubernetes + steps how to setup an instance on a local dev cluster (minikube or other) + sources used to achieve this.

**Comment by AbhijithGanesh** [comment]
@shreemaan-abhishek I am of the opinion that this issue has been taken care of and needs to be closed.

**Comment by shreemaan-abhishek** [comment]
Correct!
