### ISSUE TITLE
[Issue]: Move google docs resources to github

### ISSUE THREAD

**Issue by patchandpray** [dokc/how-to-dok#25]
### Issue

We need a more central place for the resources than google docs

### What happened?

We found out during the sync meeting that it would be better to have the resources in git

**Comment by ShivamTyagi12345** [comment]
Hi @Adwaita10 .As you are fairly new with your contributions , you can go ahead and make a Draft PR for the issue ,I will review that if it requires any changes😄Sounds good?

**Comment by Adwaita10** [comment]
@ShivamTyagi12345  Sure. Thanks a lot.

**Comment by AbhijithGanesh** [comment]
I think multiple contributors can contribute to this one issue, therefore it should really look cool. Keep contributing

**Comment by Adwaita10** [comment]
@AbhijithGanesh Yes. I'll create the basic layout and move all the current resources as of now. You can keep adding resources on the go.

**Comment by verma-kunal** [comment]
> @AbhijithGanesh Yes. I'll create the basic layout and move all the current resources as of now. You can keep adding resources on the go.

go for it

**Comment by AbhijithGanesh** [comment]
EOD it'll be there

**Comment by verma-kunal** [comment]
We have a [resources file](https://github.com/dokc/how-to-dok/blob/main/RESOURCES.md) now in the repo!! 
The basic layout looks good & we can build up as go ahead!!
