### ISSUE TITLE
We need a way to store RAP yaml contents into K8Ssandra database

### ISSUE THREAD

**Issue by patchandpray** [dokc/how-to-dok#4]
The idea is that rap lyrics, title, artist etc go in one way and then are written to the K8Ssandra database running on Kubernetes.

For this the backend code should do atleast the following:
- take RAP as an input (we can have this be a .yaml file for now)
- Ensure RAP yaml input adheres to a schema that we can write to the DB
- An interface for writing to the K8Ssandra database via stargate: https://docs.k8ssandra.io/tasks/develop/#access-graphql-data-api

We can split this up in individual tasks / pieces of code with their own inputs / outputs, or bundle them together in one application

**Comment by AbhijithGanesh** [comment]
I think this can be considered done as we've figured out storage can be done through Blob storage or other types as mentioned in the docs.

**Comment by AbhijithGanesh** [comment]
@patchandpray and @shreemaan-abhishek I think the issue #84 Will take care of this and this can be closed as well

**Comment by shreemaan-abhishek** [comment]
Also issue #64. So we should close this. Yes.
