### ISSUE TITLE
[Issue]: Typo in `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by utkarsh1311** [dokc/how-to-dok#40]
### Issue

Typo in the `git rebase` command

### What happened?

At line `43` in the `CONTRIBUTING.md` file, the command `git rebase master` should `git rebase main` as we are updating our feature branch with the `main` branch.

### Further Details

![Screenshot from 2021-12-01 15-12-10](https://user-images.githubusercontent.com/70108561/144210658-0d88cf71-ba0e-46aa-9648-ae0dbfa5bcef.png)

**Comment by Deepn05** [comment]
Should I fix this issue?
