### ISSUE TITLE
[Issue]: Rename issue template to bug

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [dokc/how-to-dok#44]
### Issue

renamming the Issue Template to bug

### What happened?

The current name does not suit the flow. It should be `ideas`, `features`, `bug`

**Comment by ashish-jaiswar** [comment]
can you assign me for this issue?

**Comment by kaiwalyakoparkar** [comment]
Sorry for the inconvinience @ashish-jaiswar this issue has already been fixed. You can take a look at other issues :slightly_smiling_face:
