### ISSUE TITLE
[FEATURE] Add Notes on topics related to the project

### ISSUE THREAD

**Issue by AmitKarnam** [dokc/how-to-dok#54]
### Would you like to have a new feature? Please describe.

I would like to add notes on few topics that can act as the staring point for new contributors.
My main focus would be on the following topics : 
1) Cloud Native
2) Containers and Docker
3) Container Orchestration and Kubernetes

### How would this feature be beneficial for the project

This feature would be the starting point for new contributors and would also help fellow contributors to learn more about a certain topic related to the project they are interested in.

### Additional context

As @patchandpray suggested in earlier meetings, This would be implemented in markdown in a separate folder that could be named Notes or anything else based on the suggestion of the community.

**Comment by shreemaan-abhishek** [comment]
@AmitKarnam all blogs are done? If yes, I think we should close this issue.

**Comment by AmitKarnam** [comment]
The last one is yet to be complete, one merged and for the other I have raised a pr
