### ISSUE TITLE
[OTHER] MicroTopic - Argo Workflows what is it, how does it work?

### ISSUE THREAD

**Issue by patchandpray** [dokc/how-to-dok#62]
### What would you like to share?

Investigate what Argo Workflows is, what it is commonly used for and how it works on Kubernetes.

Distill this down to something that we can share with the community, in the form of a blog post or via preparing a micro presentation with some slides.

**Comment by shreemaan-abhishek** [comment]
@lakshay-nasa any updates on this bro?

**Comment by lakshay-nasa** [comment]
@shreemaan-abhishek Thanks for checking in ʘ‿ʘ. This issue is closed.
You can checkout Article here. [https://github.com/dokc/how-to-dok/blob/main/resources/argo_workflows.md]()

**Comment by shreemaan-abhishek** [comment]
@lakshay-nasa, Thanks! BTW, mentioning the issue number along with the PR is recommended.
