### ISSUE TITLE
[OTHER] MicroTopic - How do I run an Argo Workflow on K3S

### ISSUE THREAD

**Issue by patchandpray** [dokc/how-to-dok#63]
### What would you like to share?

We need an example of how to run a simple argo workflow on K3S as a base starting point for implementing our own worklfow.

Can we get a document or micro presentation describing the steps that somebody needs to take to get an Argo Workflow running on K3S?

There is already good documentation out there but it would be good to have somebody show first hand experience of doing this and things that they run in to.

**Comment by yashgangwar7558** [comment]
@patchandpray I want to work on this.
