### ISSUE TITLE
[OTHER] MicroTopic - An application that writes data to cassandra

### ISSUE THREAD

**Issue by patchandpray** [dokc/how-to-dok#65]
### What would you like to share?

Can we develop a simple application that only does one thing? Write data to cassandra. It can be in any language that we prefer. 

It should take data, does not matter in which way (input file, via a web form, on the command line) and write it to a cassandra database.

Can we show the workings of this application via a blog post, document or share it via slides in a micro presentation. The code can be in this repo.

**Comment by yashgangwar7558** [comment]
@patchandpray I want to work on this issue.
