### ISSUE TITLE
[OTHER] MicroTopic - What is DevOps? and how can Kubernetes help here?

### ISSUE THREAD

**Issue by patchandpray** [dokc/how-to-dok#66]
### What would you like to share?

Can we have an investigation in what is DevOps and what the importance is of Kubernetes for DevOps?

Can we share this via a document / blog post / micro presentation?

**Comment by patchandpray** [comment]
Yes you can, go ahead.

**Comment by Vrukshali-26** [comment]
Can you assign this issue to me?

**Comment by Vrukshali-26** [comment]
Where do I need to share the blog?

**Comment by kranurag7** [comment]
@Vrukshali-26 Are you still working on this?

**Comment by Vrukshali-26** [comment]
I have written the blog in the resources directory.

**Comment by kranurag7** [comment]
Thanks for the heads up @Vrukshali-26 
I will try to contribute on other issues.
