### ISSUE TITLE
 [OTHER] MicroTopic - Build a data worfklow using Argo Worfklows

### ISSUE THREAD

**Issue by patchandpray** [dokc/how-to-dok#68]
### What would you like to share?

Build a simple data workflow using argo workflows that consists of a couple of steps that do some thing. The steps do not need to be complicated or write any data to databases. Just show how a simple workflow is developed and works.

We should have a base starting point of showing how we would build our own workflows.

An example of a workflow could be:
- write "hello world" to stdout
- the next step writes "I'm step 2" to stdout
- then next step uses the output of step 2 and uses that as its input

Go nuts. We should be able to show this in a micro presentation

**Comment by mkcr12** [comment]
@patchandpray I would like to take up this issue!

**Comment by Ridhiyanshi** [comment]
@patchandpray please can you assign me this issue.

**Comment by AbhijithGanesh** [comment]
@mkcr12 has been assigned, probably you can add your review and comments @Ridhiyanshi

**Comment by AbhijithGanesh** [comment]
Argo CD documentation - https://argo-cd.readthedocs.io/en/stable/

**Comment by AbhijithGanesh** [comment]
@shreemaan-abhishek #3 This is a duplicate issue I guess.

**Comment by shreemaan-abhishek** [comment]
Ahh yes it is 😬
