### ISSUE TITLE
[OTHER] MicroTopic - A good alternative to cassandra for our DB on Kubernetes

### ISSUE THREAD

**Issue by patchandpray** [dokc/how-to-dok#69]
### What would you like to share?

Which other Databases are there that we could use in stead of cassandra.

Maybe at some point we want to use something else versus cassandra.

Which other Databases are out there?
Which one would be good to use as Data Warehouse?

Can we get an overview of options that are out there with pro's and con's? and distill this and show this in a micro presentation?

**Comment by AmitKarnam** [comment]
@patchandpray I would like to take up this issue!

**Comment by patchandpray** [comment]
> @patchandpray I would like to take up this issue!

I assigned you, good luck!

**Comment by AmitKarnam** [comment]
Questions I am looking to answer here : 

1) What's the best way to store media files ( In our case, it's  Rap music files ) ? Store it directly to the database? Or store it as separate link in the database, while the original Rap file is stored some place else?

2) The difference in running database as per usual standard and on kubernetes.

3) Requirements for running DB on Kubernetes.

4) The previous use cases running the choosedn dB on Kubernetes.

**Comment by AbhijithGanesh** [comment]
Amit I might have few answers.

1. We are going to receive it as `yaml` files and these yaml files need to be subsequently stored 
2. Operationally there is an extra layer of security with k8s

**Comment by patchandpray** [comment]
We might also consider to take the text from the content from the yaml files and store it based on key/value.

**Comment by AmitKarnam** [comment]
From what I understand here , is that we need to answer the question of how we plan to design our database and how we plan to store our data.

As K8's has evolved to handle databases,  we need to first take a call on our dB

Also the basic requirement for running a dB on k8's is that it has a image we can pull frm a container registry and use.This is not a big problem as many of the popular databases have their official images.

The second aspect here is the use of operators to run our dB on k8's , which makes the whole process of running db on k8's easy, few of the popular db's provide this also, ex postgres has Kubegres.

Any other aspects I'm missing here?

Cc : @AbhijithGanesh , @patchandpray

**Comment by AbhijithGanesh** [comment]
We'll be sticking to Cassandra (most-likely) and I am not sure about the operators as of now as it will be a bigger process to implement and more documentation will be required. We need to see the merits and demerits before we make a decision.

**Comment by AmitKarnam** [comment]
> We'll be sticking to Cassandra (most-likely) and I am not sure about the operators as of now as it will be a bigger process to implement and more documentation will be required. We need to see the merits and demerits before we make a decision.

@AbhijithGanesh I think through this issue, we are trying to find an alternative for cassandra and may be use it in our project?
Please clarify.

**Comment by akshitadixit** [comment]
considering this was assigned long ago, is this still being worked upon?

**Comment by AbhijithGanesh** [comment]
@AmitKarnam Would you like to suggest alternatives or can this issue be closed?

**Comment by AmitKarnam** [comment]
I think it's good to go with Cassandra. We can move to close this issue!
