### ISSUE TITLE
[OTHER] MicroTopic - How do we build and push our custom docker images to a central repository?

### ISSUE THREAD

**Issue by patchandpray** [dokc/how-to-dok#70]
### What would you like to share?

We need an example of how we can build and push what we build as docker containers (images) to a repository so that our kubernetes clusters can use these docker images.

How do we do this?

Can we get an example / blog post/ document describing how to do this with a micro presentation on the subject?

**Comment by Vrukshali-26** [comment]
@ShivamTyagi12345 are you still working on this issue?

**Comment by ShivamTyagi12345** [comment]
> @ShivamTyagi12345 are you still working on this issue?

Thanks for Checking In:) Yes I am working on this issue. But Would appreciate it if u can review my PR as soon as I am done with it

**Comment by Vrukshali-26** [comment]
Yaa sure! Will do that.

**Comment by ShivamTyagi12345** [comment]
@Vrukshali-26  if u r still interested please do take up this issue:) I am a bit occupied with few other commitments at the moment

**Comment by Vrukshali-26** [comment]
No issues! I'll work on this!

**Comment by AbhijithGanesh** [comment]
Are we planning to use GitHub to push docker images? Any thoughts @Vrukshali-26 and @ShivamTyagi12345

**Comment by ShivamTyagi12345** [comment]
We do have  GitHub Container Registry .Doesn't that align with our requirements here @AbhijithGanesh

**Comment by AbhijithGanesh** [comment]
It certainly does, usually the practice is to push it to DockerHub, but GitHub came up with their own provision to work with Images, thats why I asked.

Since we'll be working with GitHub, can you and @Vrukshali-26 work on establishing the repository/directory/provisions to facilitate image sharing.

**Comment by ShivamTyagi12345** [comment]
> It certainly does, usually the practice is to push it to DockerHub, but GitHub came up with their own provision to work with Images, thats why I asked.
> 
> Since we'll be working with GitHub, can you and @Vrukshali-26 work on establishing the repository/directory/provisions to facilitate image sharing?

sure sounds good

**Comment by Vrukshali-26** [comment]
> It certainly does, usually the practice is to push it to DockerHub, but GitHub came up with their own provision to work with Images, thats why I asked.
> 
> Since we'll be working with GitHub, can you and @Vrukshali-26 work on establishing the repository/directory/provisions to facilitate image sharing?

Okay!

**Comment by AbhijithGanesh** [comment]
@Vrukshali-26 are you making a blog here or in a platform like dev.to?

**Comment by Vrukshali-26** [comment]
I'm making In resources directory

**Comment by AbhijithGanesh** [comment]
@Vrukshali-26 I am closing the issues as the PR has been merged
