### ISSUE TITLE
[OTHER] MicroTopic - Database model for RAP's

### ISSUE THREAD

**Issue by patchandpray** [dokc/how-to-dok#71]
### What would you like to share?

If we are going to store data about the RAP's in a database we have to think about how we are going to store it.

With regards to any data about the rap's can we come up with:
- what we can store
- what we want to store
- how would that looke like in a datamodel

The outcome of this story should be answers to the above questions in a format that we can reference (markdown file)
with a datamodel (in yaml / json/ avro / sqlor maybe even in code?)
some slides about this topic that we can present in a micropresentation

### Additional information

When thinking about a datamodel remember that we would need at least these:
- the name of the field / column (ie: user, video_url, lyrics)
- the data type of that column (text, string, integer, boolean etc)
- the description of that field/column( ie: video_url: url pointing to the video online)
- If the field can be null, (empty)

**Comment by AbhijithGanesh** [comment]
@patchandpray I think for the DB Schema, We need to come up with an extensive mapping of the same and we need to save it in our contributing/docs guide. I think @birthmarkbart will have to help us with this.

**Comment by AbhijithGanesh** [comment]
I think the issue  #84 encapsulates this, probably we can convert this issue into making documentation or make a new one related to documentation

**Comment by shreemaan-abhishek** [comment]
We kinda have a lot of issues just for getting rap lyrics into the DB 👀
