### ISSUE TITLE
[FEATURE] Notify slack channel of new issues

### ISSUE THREAD

**Issue by patchandpray** [dokc/how-to-dok#72]
### Would you like to have a new feature? Please describe.

Can we automatically post new issues that are created here to the slack channel so everbody can see them?

How would we do this, do we have to build our own bot or is there already an integration for github/slack that we can use?

How would we configure this?

### How would this feature be beneficial for the project

It would improve our workflow by improving visibilty over issues in the repository

**Comment by Polokghosh53** [comment]
There is way actually. Do refer to this link: https://github.com/integrations/slack if it feels relevant to you.

**Comment by AmitKarnam** [comment]
Is our aim to achieve something similar to that achieved in eddiehub discord server, where they have a github channel to bring the live updates on github repo to their discord channel?

**Comment by Polokghosh53** [comment]
> Is our aim to achieve something similar to that achieved in eddiehub discord server, where they have a github channel to bring the live updates on github repo to their discord channel?

Yes, we are looking for something like where we will receive updates regarding our repo automatically than manually so that we keep ourselves updated with the issues that are dropping.

**Comment by patchandpray** [comment]
For me initially only notifications in the case new issues are created are enough. No other updates yet, this can cause update fatigue.

**Comment by AbhijithGanesh** [comment]
@patchandpray Do we not have a github extension which does this?

**Comment by Vrukshali-26** [comment]
Is anyone working on this issue?
I have found this https://zapier.com/apps/github/integrations/slack/396/get-slack-notifications-for-new-github-issues

**Comment by AmitKarnam** [comment]
> Is anyone working on this issue?
> I have found this https://zapier.com/apps/github/integrations/slack/396/get-slack-notifications-for-new-github-issues

It's a paid service,  need to talk to other members regarding this.
Can we come up with a simple automation script for this as a temporary solution?

**Comment by Vrukshali-26** [comment]
I have found some resources lile we can do this by github actions.

**Comment by akshitadixit** [comment]
Is this being worked upon?

**Comment by AbhijithGanesh** [comment]
@akshitadixit It is being worked on, it is more of a feature addition.

**Comment by AbhijithGanesh** [comment]
@birthmarkbart Has fixed this! This issue is closed

**Comment by Polokghosh53** [comment]
Great🤜🤛 @AbhijithGanesh !!
