### ISSUE TITLE
Addition of various social media links of dok community.

### ISSUE THREAD

**Issue by gullapalli9482** [dokc/how-to-dok#74]
### Would you like to have a new feature? Please describe.

Including a section wherein , folks going through the readme file could follow accounts of dok community by including icons or links navigating the users to the "dok community's" social media accounts.

### How would this feature be beneficial for the project

This would be really helpful for those:
-> Visiting the github page for the very first time.
-> Really helpful in gathering audience or folks towards the community.
->Helpful for folks looking for some talks or more content that the community delivers from time to time.(Youtube channel)

**Comment by gullapalli9482** [comment]
I would like to work on this, do assign me ,for doing it

**Comment by shreemaan-abhishek** [comment]
@gullapalli9482 assigned it to you :)

**Comment by AbhijithGanesh** [comment]
@gullapalli9482 Will you be adding this to the readme file? If you need any help feel free to reach out!

**Comment by Anubhavdevv** [comment]
I would also like to work on this issue

**Comment by shreemaan-abhishek** [comment]
@gullapalli9482, are you actively working on this?

**Comment by gullapalli9482** [comment]
I would be working on this real soon.
it'll be done mostly by this  weekend.
