### ISSUE TITLE
[DOCS] Add Componenets as bullet points

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [dokc/how-to-dok#78]
### Would you like to have a new feature? Please describe.

The components section looks like a single block of text. If we add bullet points to each component description then it will be easer to read and refer
![example image](https://i.imgur.com/8uAsuEo.png)

**Comment by chaitanya-24** [comment]
Hello @kaiwalyakoparkar, I would like to solve this issue.

**Comment by kaiwalyakoparkar** [comment]
Sure @chaitanya-24, go ahead :)

**Comment by Anubhavdevv** [comment]
Hey, @kaiwalyakoparkar I would also like to work on this issue !!

**Comment by AbhijithGanesh** [comment]
@shreemaan-abhishek I think this issue can be closed, the error has been patched.
