### ISSUE TITLE
Template for Issue, Idea and Bug

### ISSUE THREAD

**Issue by AbhijithGanesh** [dokc/how-to-dok#8]
We need a .yml template for Issues, Ideas,Q and A, bug. This would streamline our process of development.

**Comment by AbhijithGanesh** [comment]
Continuing the Slack conversation here, I am working on the .yml files

**Comment by AbhijithGanesh** [comment]
It works on my repo perfectly. @kaiwalyakoparkar (I lost track of your mention elsewhere)

**Comment by kaiwalyakoparkar** [comment]
@AbhijithGanesh I was asking if you can enable issue tab on your forked repo so that we can test out this template

**Comment by AbhijithGanesh** [comment]
> @AbhijithGanesh I was asking if you can enable issue tab on your forked repo so that we can test out this template

I enabled it yesterday, and it can be tested there @kaiwalyakoparkar . I have also pushed the other yml files

**Comment by kaiwalyakoparkar** [comment]
> > @AbhijithGanesh I was asking if you can enable issue tab on your forked repo so that we can test out this template
> 
> I enabled it yesterday, and it can be tested there @kaiwalyakoparkar . I have also pushed the other yml files

Thanks, comment added

**Comment by verma-kunal** [comment]
i think we can also use templates from EddieHub Community!! (with a little modifications)
https://github.com/EddieHubCommunity/support/tree/main/.github/ISSUE_TEMPLATE

They are nicely structured
what do you think? 
cc @kaiwalyakoparkar @patchandpray

**Comment by AbhijithGanesh** [comment]
Would you like me to restructure it like the Eddie Hub Community forms? @verma-kunal

**Comment by verma-kunal** [comment]
> Would you like me to restructure it like the Eddie Hub Community forms? @verma-kunal

you have already made a PR for `issue.yaml`, right!! So, i think thats good to go for now (do make sure to add the necessary changes suggested by @kaiwalyakoparkar, in order for that to be ready to merge)

For the other files, we can take help from EddieHub's templates, but let's take other's opinions as well on this!🙂

**Comment by AbhijithGanesh** [comment]
I have tried implementing the changes Kaiwalya had suggested, I just didn't understand which emote he was talking about and it was confusing😅
