### ISSUE TITLE
[FEATURE]: How to retrieve super-user credentials

### ISSUE THREAD

**Issue by AbhijithGanesh** [dokc/how-to-dok#94]
### Would you like to have a new feature? Please describe.

Currently, the documentation doesn't cover how to retrieve super-user credentials and how to use them with the stargate API to retrieve data. One needs to create docs about how to retrieve the credentials 

### How would this feature be beneficial for the project

This would make it easier for developers to access the stargate API.

### Additional context

The following 4 tasks need to be covered:
 - [ ] Document how to get credentials (using `kubectl secrets`)
 `kubectl get secrets <deployment/cluster-name>-superuser -o jsonpath={.data.username/password}`
 - [ ] Document how to decode the token retrieved using base64
 - [ ] Document how to post the data to a certain port through which the auth is exposed
 - [ ] Show an example of the token returned by Stargate post-authentication

**Comment by AbhijithGanesh** [comment]
@yashgangwar7558 was just working on this, Would you like to take the issue?

**Comment by yashgangwar7558** [comment]
@AbhijithGanesh I would like to work on this.
